version: '3'

services: 
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/configuration:/etc/nginx/conf.d/
      - ./:/var/www/portfoliov3/
    restart: always
    
nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/configuration:/etc/nginx/conf.d/
      - ./:/var/www/portfoliov3/
    restart: always